### ISSUE TITLE
.universe confusion

### ISSUE THREAD

**Issue by PeterJensen** [sunfishcode/ecmascript_simd#1]
I'm a  little confused by the operations in the .universe namespace.  I assume there will be min/max operations in this namespace that mimics all the different semantics of the various CPU architecture semantics that we care about as well as operations that are only available on some architectures, like fma (AVX/Neon).  If the semantics of the fma operation is slightly different between AVX and Neon (e.g. subnormal handling)  will there be two differently named .fma operations?

I'm not a 100% certain it's always possible to mimic missing functionality with a polyfill (still thinking about an example).

Also, the .universe name itself is probably a little confusing.  How about .special?

**Comment by sunfishcode** [comment]
I expect min/max will be best handled through the .relaxed half of the proposal, because these fall into the category of operations which are available most everywhere with only minor semantic differences. I'm inclined to say that we don't need to put operations in .universe if they're satisfactorily covered in either the base namespace or the .relaxed namespace, but that's discussable.

On the topic of subnormal handling, we already face this problem throughout the entire SIMD.js API, because 32-bit ARM NEON is hardwired to flush subnormals to zero. I believe our strategy is that we're just going to say that it's unspecified whether subnormals are flushed to zero (on input, output, and any implied intermediate values) in _any_ SIMD.js API call, although I don't remember when we last discussed it. This is an unfortunate solution to be sure, but we're up against some hard constraints on this topic.

To address your broader question, my inclination would be to say that, yes, the .universe namespace should have separate functions if there are differences in semantics (and if it doesn't make sense to move them to .relaxed). Part of my theory is that these should be relatively rare.

Examples of instructions which don't fit into this proposal would be very useful.

One example of an instruction that doesn't fit is cvtss2si, because this depends on the rounding mode, however exposing a new kind of global state is going to be problematic independently of this proposal, so I've not worried about it.

I like .universe because it describes its intention to include instructions from all planets in the SIMD universe, including the x86 and ARM planetary systems, and whatever else is out there to be discovered. It's a union-style API, to contrast the base namespace's intersection-style API. How does that sound? :-)

**Comment by sunfishcode** [comment]
The extended API proposal is now [in the main repo](https://github.com/johnmccutchan/ecmascript_simd/blob/master/extended-api.md), so if there are further questions or concerns, please file issues [there](https://github.com/johnmccutchan/ecmascript_simd/issues).
